version: '3.8'
services:
  app:
    image: python:3.8-alpine
    tty: true
    volumes:
      - ../:/app/
      - user-scripts:/app/user-scripts-shared/
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - python-runner
      - cpp-runner

  python-runner:
    image: python:3.8-alpine
    extends:
      file: docker-compose.common.yml
      service: common-runner
    deploy:
      replicas: 3

  cpp-runner:
    image: frolvlad/alpine-fpc:latest
    extends:
      file: docker-compose.common.yml
      service: common-runner
    deploy:
      replicas: 3

volumes:
  user-scripts:
