version: '3.8'
services:
  driver:
    container_name: CONTESTER.Driver
    image: contester-driver
    build:
      context: .
    volumes:
      - user-scripts-volume:/app/${LOCAL_USER_SCRIPTS_DIR}/
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - DOCKER_FLAG=1

volumes:
  user-scripts-volume:
